# ---
# resources:
# - name: every-week
#   type: time
#   icon: clock-outline
#   source:
#     interval: 168h
# - name: source
#   type: git
#   source:
#     uri: https://gitea.redxef.at/redxef/nginx-envsubst
#     branch: master
# - name: image
#   type: registry-image
#   source:
#     username: ((docker.username))
#     password: ((docker.password))
#     repository: redxef/nginx-envsubst
#     tag: latest


# jobs:
# - name: build-push
#   plan:
#   - get: every-week
#     trigger: true
#   - get: source
#     trigger: true
#   - task: build
#     privileged: true
#     config:
#       platform: linux
#       image_resource:
#         type: registry-image
#         source:
#           repository: concourse/oci-build-task
#       inputs:
#       - name: source
#         path: .
#       params:
#         IMAGE_PLATFORM: linux/amd64
#       outputs:
#       - name: image
#       run:
#         path: build
#   - put: image
#     params:
#       image: image/image.tar


---
resources:
- name: source
  type: git
  source:
    uri: https://gitea.redxef.at/redxef/nginx-envsubst
    branch: master
- name: upstream-image
  type: registry-image
  source:
    repository: alpine

jobs:
- name: build-push
  plan:
  - get: source
    trigger: true
  - get: upstream-image
    trigger: true
  - task: compute-docker-tags
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: alpine/git
      inputs:
      - name: source
        path: .
      outputs:
      - name: docker-tags
      run:
        path: sh
        args:
        - -c
        - |
          #!/usr/bin/env sh
          git rev-parse --short HEAD > docker-tags/tags.txt
  - task: build
    privileged: true
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: redxef/concourse-buildkit
      inputs:
      - name: source
        path: .
      - name: docker-tags
      params:
        username: ((docker.username))
        password: ((docker.password))
        repository: docker.io/redxef/nginx-envsubst
        tag: latest
        additional_tags: docker-tags/tags.txt
        push: true
        platform: aarch64,arm,i386,ppc64le,s390x,x86_64
        context: .
        manual: false
      run:
        path: build

